### ISSUE TITLE
Request to remove invalid characters when decoding base64 

### ISSUE THREAD

**Issue by marcg1** [Leworoe/thunderbird-outlook-appointment#8]
Please consider removing invalid characters when decoding the base64-decoded invite.

An invite that I received in Thunderbird and saved via the Outlook/Teams Appointment plugin resulted in a .ics file that could not be imported to Google calendar.  Running `base64` directly on the base64-encoded invite block from the message yielded the same result.  Running `base64 -i` on the encoded invite block yielded an importable invite.

Thanks for a great Thunderbird extension!

**Comment by Leworoe** [comment]
I need more information. Which version of the extension did you use? The version 1.1 resolved issues with utf8 characters.
I can not reproduce your problem, it would be great if I can get an .eml file of the broken invite, so I can direcly debug on that.
You can export the email as an .eml file here:
![image](https://user-images.githubusercontent.com/45066937/162531994-ccc0824f-cdc3-4ba5-b891-19e04361832c.png)

**Comment by marcg1** [comment]
I was using version 1.1.  I have a sample .eml, but it contains some PII -- names and email addresses -- that I'd rather not post here.  I reached out to you on LinkedIn.  Once we connect there, I can send you a copy privately. 

Thanks!

**Comment by Leworoe** [comment]
Thank you for sharing your email. The problem was that in the email there were two base64 encoded blocks and the code did not address that particular occurrence. I have fixed it in the commit [e9c31ac](https://github.com/Leworoe/thunderbird-outlook-appointment/commit/e9c31aca899680f1e2b9127fe07fc785e574b172). I will see that I release a new version in the next few days.
